AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Anonymous Articles Backend

Parameters: 
  BillingTag: 
    Type: String
    Default: alinea
    Description: a parameter that define billing tag sued on project
  LogRetentionInDays:
    Type: Number
    Default: 7
    Description: a log retention days

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Environment:
      Variables:
        ARTICLES_TABLE: !Ref ArticlesTable
        CORS_ORIGIN: '*'
    Tags:
      billing: !Ref BillingTag

Resources:
  # DynamoDB Table for Articles
  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-articles"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CreatedAtIndex
          KeySchema:
            - AttributeName: createdAt
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: 'billing'
          Value: !Ref 'BillingTag'

  # Lambda Functions
  ArticlesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: articles.handler
      Events:
        CreateArticle:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /articles
            Method: post
        GetRandomArticles:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /articles/random
            Method: get            
        LikeArticle:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /articles/{id}/like
            Method: post            
        ShareArticle:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /articles/{id}/share
            Method: post       
        ViewArticle:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /articles/{id}/view
            Method: post
        # CORS OPTIONS handlers
        OptionsArticles:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /articles
            Method: options
        OptionsArticlesRandom:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /articles/random
            Method: options
        OptionsArticlesLike:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /articles/{id}/like
            Method: options
        OptionsArticlesShare:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /articles/{id}/share
            Method: options
        OptionsArticlesView:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /articles/{id}/view
            Method: options
        # Report Abuse endpoint
        ReportAbuse:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /report-abuse
            Method: post
        OptionsReportAbuse:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /report-abuse
            Method: options
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ArticlesTable
  # CloudWatch Log Group for the Articles Function
  ArticlesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ArticlesFunction}
      RetentionInDays: !Ref LogRetentionInDays
      Tags:
        - Key: 'billing'
          Value: !Ref 'BillingTag'

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"